apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-todo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PratapSingh13/argo-app.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
