apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: monitoring
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: pratapsingh13/todo-app:2022-12-21-14-32-09-34
        ports:
        - containerPort: 8000
