apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: monitoring
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: pratapsingh13/todo-app:2022-12-20-21-58-49-27
        ports:
        - containerPort: 8000
