---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
  selector:
    app: todo-app
